<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix = "c" uri = "http://java.sun.com/jsp/jstl/core" %>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1" isELIgnored="false"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
		<title>Login page</title>
		<style>
			i {
				color: red;
				font-family: cursive;
			}
			
			h3 {
			    color: green;
				font-family: cursive;
			}
			
			a {
				background-color: black;
				color: white;
			}
		</style>
	</head>
	
	<body>
	
		<c:if test="${param.error != null}">
			<i> BAD CREDENTIALS, Invalid username and password</i>
		</c:if>
		
		<c:if test="${param.logout != null}">
			<i> You are successfully logged out, Sign in again..</i>
		</c:if>
		<br />
		
		<div align="center">
			<h3>Custom Login page</h3>
			<h3> NewUser..? </h3>
			<a href="/spring-security/signUpPage"> SIGN-UP </a>
		</div>
		<br/>
	
		<form:form action="process-login" method = "POST"> 
			<%--  Result in browser : <form id="command" action="/process-login" method="POST"> --%>
			
		<%-- <form:form> --%>
			<%--  Result in browser : <form id="command" action="/spring-security/myCustomLoginPage" method="post"> --%>
	
			<label> USERNAME : </label>
			<input type="text" name="myUsername">
			<br> <br>
			
			<label> PASSWORD : </label>
			<input type="password" name="myPassword">
			<br> <br>
			
			<input type="submit" value="LOGIN">
	
			<!-- INTERNALLY CSRF TOKEN GENERATED BY SPRING SECURITY LIKE THIS -->
			<!--  <input type="hidden" name="_csrf" value="8f7fc3d0-2b3f-4529-9725-89d412ad9252"> -->
		</form:form>
	</body>
</html>